#!/bin/bash

command=$1
arguments="${@:2}"
basedir=$(dirname "$0")
pwd=$(pwd)

allowed="train train2 test test_own_scipy data sweep param_search"

if ! [[ $allowed =~ (^|[[:space:]])"$command"($|[[:space:]]) ]]; then
  echo "ERROR: unknown command $command"
  exit 1
fi

echo $PYTHONPATH
python $basedir/nabu/scripts/prepare_$command.py $arguments
